# Generated by Django 4.2.15 on 2024-09-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Average',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('g_per_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_01', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_02', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_03', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_04', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_05', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_06', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_07', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_08', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_09', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_10', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_11', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_12', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
